config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get 'welcome/about', to: 'welcome#about'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/contacts', to: 'welcome#contacts'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :categories, except: [:destroy]
  resources :recipes
  resources :responses
  resources :discussions
  resources :products
  resources :posts
  resources :users, except: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :responses
  has_many :discussion_categories
  has_many :categories, through: :discussion_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :question, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(title: discussion_params[:title],
                                question: discussion_params[:question],
                                category_ids: discussion_params[:category_ids],
                                user_id: current_user.id)
                                
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :question, category_ids: [])
    end

    def require_same_user
      if current_user != @discussion.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.erb
    <% obj.each do |discussion| %>

          <div class="well well-lg each_box">
            <div class="discussion-title">
              <%= link_to discussion.title, discussion_path(discussion) %>
            </div>
            <div class="discussion-body">
                <%= truncate(discussion.question, length: 100) %>
            </div>
            <% if discussion.categories.any? %>
             <p>Categories: <%= render discussion.categories %></p>
            <% end %>
            <% if logged_in? && (current_user == discussion.user || current_user.admin?) %>
              <div class="discussion-actions">
                <%= link_to "Edit this topic", edit_discussion_path(discussion), class: "btn btn-xs btn-success", id: "butt" %>
                <%= link_to "Delete this topic", discussion_path(discussion), method: :delete,
                          data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger", id: "butt" %>
              </div>
            <% end %>

            <%= discussion.user.username %>
          </div>
    
    <% end %>

app/views/discussions/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@discussion, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @discussion.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@discussion.errors.count, "error") %>
              prohibited this discussion from being saved:
            </h2>

            <div class="panel-body">
              <ul>
                <% @discussion.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-11">
          <%= f.text_field :title, class: 'form-control', placeholder: "Title of discussion", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :question %>
        </div>
        <div class="col-md-11">
          <%= f.text_area :question, rows: 10, class: 'form-control', placeholder: 'Body of discussion' %>
        </div>
      </div>
      <% current_user == discussion.user %>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1 align="center">Discussions</h1>
<div class="discussion_wrapper">
  <%= render 'discussion', obj: @discussions %>
</div>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<h2 align="center"> Title: <%= @discussion.title %></h2>
<div align="center">
  <ul class="listing">
    <li>Created by:</li>
    <div class="row">
      <li><%= link_to gravatar_for(@discussion.user), user_path(@discussion.user)%></li>
      <li class="discussion-title">
        <%= link_to @discussion.user.username, user_path(@discussion.user) %>
      </li>
    </div>
  </div>
</ul>
  <h4 class="center"><strong>Question:</strong></h4>
    <hr>
    <%= simple_format(@discussion.question) %>
    <% if @discussion.categories.any? %>
      <p>Categories: <%= render @discussion.categories %></p>
    <% end %>
    <% if logged_in? && (current_user == @discussion.user || current_user.admin?) %>
      <div class="discussion-actions">
        <%= link_to "Edit this topic", edit_discussion_path(@discussion), class: "btn btn-xs btn-danger", id: "butt" %>
        <%= link_to "Delete this topic", discussion_path(@discussion), method: :delete,
                  data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger", id: "butt" %>
      </div>
    <% end %>
</div>