config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get 'welcome/about', to: 'welcome#about'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/contacts', to: 'welcome#contacts'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :categories, except: [:destroy]
  resources :recipes
  resources :responses
  resources :discussions
  resources :products
  resources :posts
  resources :users, except: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :discussions
  has_many :responses
  has_many :categories

  before_save { self.email = email.downcase }
  
  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
        
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, 
    presence: true, 
    length: {maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
    
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_adin, only: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end

    def require_adin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin users can preform that action"
        redirect_to root_path
      end
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :username %>
        </div>
        <div class="col-md-11">
          <%= f.text_field :username, class: 'form-control', placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :email %>
        </div>
        <div class="col-md-11">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email' %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :password %>
        </div>
        <div class="col-md-11">
          <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg pull-right') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to home page", welcome_home_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit user info</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', signup_path %>

app/views/users/index.html.erb
<h1 align="center">All Digest Digesters</h1>
<div align="center">
  <%= @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user)%></li>
          <li class="discussion-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.discussions.count, "discussion") if user.discussions %></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
              data: { confirm: "Are you sure you want to delete the user and all of their discussions?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Digest Digest</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user %>
  </div>
<div class="col-md-4 col-md-offset-4 center">
  <strong>Username:</strong>
  <%= @user.username %>
</div>

<div class="col-md-4 col-md-offset-4 center">
  <strong>Email:</strong>
  <%= @user.email %>
</div>

<div class="col-md-4 col-md-offset-4 center">
  <%= @user.username %>'s discussions:</h4>
  <%= render 'discussions/discussion', obj: @user.discussions %>
</div>
<div align="center">
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', signup_path %>
</div>