config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get 'welcome/about', to: 'welcome#about'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/contacts', to: 'welcome#contacts'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :categories, except: [:destroy]
  resources :recipes
  resources :responses
  resources :discussions
  resources :products
  resources :posts
  resources :users, except: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      An MMODAK on Rails site
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", welcome_home_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<div class="container">
    <nav class="navbar navbar-light" style="background-color: #E6E6FA;">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "The Digest Digest", welcome_home_path, class: "navbar-brand", id: "logo" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <!-- <li class="active"><a href="#">Home</a></li> -->
              <li class="active"><%= link_to "Home", welcome_home_path %></li>
              <li> <%= link_to "About", welcome_about_path %></li>
              <!-- <li><a href="#">About</a></li> -->


            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My blog <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Blog posts", posts_path %></li>
                  <li><%= link_to "Most recent post", posts_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Discussions <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Discussion board", discussions_path %></li>
                  <li><%= link_to "Most recent discussion", discussions_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to "Create new discussion", new_discussion_path %></li>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Recipes", recipes_path %></li>
                  <li><%= link_to "Most recent recipe", recipes_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to "New recipe", new_recipe_path %></li>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Profile<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if logged_in? %>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                    <li>Current <%= "Admin" if current_user.admin? %> user: <%= link_to current_user.username, user_path(current_user) %></li>
                  <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                    <li><%= link_to "Sign up", signup_path %></li>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "All Categories", categories_path %></li>
                  <% Category.all.each do |category| %>
                    <li><%= link_to "#{category.name}", category_path(category) %></li>
                  <% end %>
                  <li role="separator" class="divider"></li>
                  <% if logged_in? && current_user.admin? %>
                    <li><%= link_to "New Category", new_category_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigestDigest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='home-body'>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>